/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "rtwtypes.h"


#include "EstimateNoiseW.h"
#include "EstimateNoiseW_terminate.h"
#include "EstimateNoiseW_initialize.h"
#include "EstimateNoiseW_types.h"
//nothings


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1p_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->p;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1p_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->p);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1ac_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->ac = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_LocalState_1ac_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T) ((arg1)->ac);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1sn2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->sn2;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1sn2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->sn2);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1pb_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->pb;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1pb_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->pb);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1pb2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->pb2;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1pb2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->pb2);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1pminu_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->pminu;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1pminu_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->pminu);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1actmin_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->actmin;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1actmin_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->actmin);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1actminsub_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    real_T *b = (real_T *) arg1->actminsub;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1actminsub_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->actminsub);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1subwc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->subwc = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_LocalState_1subwc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T) ((arg1)->subwc);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1actbuf_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = *(real_T **)&jarg2; 
  {
    size_t ii;
    real_T *b = (real_T *) arg1->actbuf;
    for (ii = 0; ii < (size_t)2056; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_LocalState_1actbuf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->actbuf);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1ibuf_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->ibuf = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_LocalState_1ibuf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T) ((arg1)->ibuf);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1lminflag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jobject jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  boolean_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  {
    arg2 = (boolean_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg2);
  }
  {
    size_t ii;
    boolean_T *b = (boolean_T *) arg1->lminflag;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((boolean_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jobject JNICALL Java_EstimateNoiseMWJNI_LocalState_1lminflag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jobject jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  boolean_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (boolean_T *)(boolean_T *) ((arg1)->lminflag);
  *(boolean_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1nrcum_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->nrcum = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_LocalState_1nrcum_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T) ((arg1)->nrcum);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_LocalState_1tinc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  LocalState *arg1 = (LocalState *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->tinc = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_LocalState_1tinc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  LocalState *arg1 = (LocalState *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(LocalState **)&jarg1; 
  result = (real_T) ((arg1)->tinc);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1LocalState(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  LocalState *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (LocalState *)calloc(1, sizeof(LocalState));
  *(LocalState **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1LocalState(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  LocalState *arg1 = (LocalState *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(LocalState **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (void *) ((arg1)->data);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_EstimateNoiseMWJNI_emxArray_1_1common_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1_1common(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray__common *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray__common *)calloc(1, sizeof(emxArray__common));
  *(emxArray__common **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1_1common(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray__common **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_118_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_18 *arg1 = (emxArray_int32_T_18 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_18 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->data;
    for (ii = 0; ii < (size_t)18; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_118_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_18 *arg1 = (emxArray_int32_T_18 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_18 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->data);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_118_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_18 *arg1 = (emxArray_int32_T_18 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_18 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->size;
    for (ii = 0; ii < (size_t)1; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_118_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_18 *arg1 = (emxArray_int32_T_18 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_18 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1int32_1T_118(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_int32_T_18 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_int32_T_18 *)calloc(1, sizeof(emxArray_int32_T_18));
  *(emxArray_int32_T_18 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1int32_1T_118(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_int32_T_18 *arg1 = (emxArray_int32_T_18 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_int32_T_18 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x257_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_1x257 *arg1 = (emxArray_int32_T_1x257 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x257 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->data;
    for (ii = 0; ii < (size_t)257; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x257_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x257 *arg1 = (emxArray_int32_T_1x257 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x257 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->data);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x257_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_1x257 *arg1 = (emxArray_int32_T_1x257 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x257 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->size;
    for (ii = 0; ii < (size_t)2; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x257_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x257 *arg1 = (emxArray_int32_T_1x257 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x257 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1int32_1T_11x257(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x257 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_int32_T_1x257 *)calloc(1, sizeof(emxArray_int32_T_1x257));
  *(emxArray_int32_T_1x257 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1int32_1T_11x257(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_int32_T_1x257 *arg1 = (emxArray_int32_T_1x257 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_int32_T_1x257 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x4_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_1x4 *arg1 = (emxArray_int32_T_1x4 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x4 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->data;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x4_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x4 *arg1 = (emxArray_int32_T_1x4 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x4 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->data);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x4_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_1x4 *arg1 = (emxArray_int32_T_1x4 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x4 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->size;
    for (ii = 0; ii < (size_t)2; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_11x4_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x4 *arg1 = (emxArray_int32_T_1x4 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_1x4 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1int32_1T_11x4(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_int32_T_1x4 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_int32_T_1x4 *)calloc(1, sizeof(emxArray_int32_T_1x4));
  *(emxArray_int32_T_1x4 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1int32_1T_11x4(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_int32_T_1x4 *arg1 = (emxArray_int32_T_1x4 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_int32_T_1x4 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_14_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_4 *arg1 = (emxArray_int32_T_4 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_4 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->data;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_14_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_4 *arg1 = (emxArray_int32_T_4 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_4 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->data);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_14_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T_4 *arg1 = (emxArray_int32_T_4 *) 0 ;
  int32_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_4 **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  {
    size_t ii;
    int32_T *b = (int32_T *) arg1->size;
    for (ii = 0; ii < (size_t)1; ii++) b[ii] = *((int32_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1int32_1T_14_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T_4 *arg1 = (emxArray_int32_T_4 *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T_4 **)&jarg1; 
  result = (int32_T *)(int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1int32_1T_14(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_int32_T_4 *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_int32_T_4 *)calloc(1, sizeof(emxArray_int32_T_4));
  *(emxArray_int32_T_4 **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1int32_1T_14(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_int32_T_4 *arg1 = (emxArray_int32_T_4 *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_int32_T_4 **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  real_T *arg2 = (real_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = *(real_T **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (real_T *) ((arg1)->data);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_EstimateNoiseMWJNI_emxArray_1real_1T_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1emxArray_1real_1T(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_real_T *)calloc(1, sizeof(emxArray_real_T));
  *(emxArray_real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1emxArray_1real_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_real_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1taca_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->taca = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1taca_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->taca);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tamax_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->tamax = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tamax_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->tamax);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1taminh_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->taminh = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1taminh_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->taminh);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tpfall_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->tpfall = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tpfall_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->tpfall);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tbmax_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->tbmax = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1tbmax_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->tbmax);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qeqmin_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->qeqmin = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qeqmin_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->qeqmin);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qeqmax_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->qeqmax = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qeqmax_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->qeqmax);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1av_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->av = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1av_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->av);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1td_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->td = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1td_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->td);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1nu_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jdouble jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = (real_T)jarg2; 
  if (arg1) (arg1)->nu = arg2;
}


SWIGEXPORT jdouble JNICALL Java_EstimateNoiseMWJNI_struct_1T_1nu_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jdouble jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T) ((arg1)->nu);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qith_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = *(real_T **)&jarg2; 
  {
    size_t ii;
    real_T *b = (real_T *) arg1->qith;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_struct_1T_1qith_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->qith);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_struct_1T_1nsmdb_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct_T *arg1 = (struct_T *) 0 ;
  real_T *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  arg2 = *(real_T **)&jarg2; 
  {
    size_t ii;
    real_T *b = (real_T *) arg1->nsmdb;
    for (ii = 0; ii < (size_t)4; ii++) b[ii] = *((real_T *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_struct_1T_1nsmdb_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct_T *arg1 = (struct_T *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct_T **)&jarg1; 
  result = (real_T *)(real_T *) ((arg1)->nsmdb);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_EstimateNoiseMWJNI_new_1struct_1T(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct_T *)calloc(1, sizeof(struct_T));
  *(struct_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_delete_1struct_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct_T *arg1 = (struct_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_EstimateNoiseW(JNIEnv *jenv, jclass jcls, jobject jarg1, jlong jarg2, jobject jarg2_, jobject jarg3) {
  real_T *arg1 ;
  LocalState *arg2 = (LocalState *) 0 ;
  real_T *arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg2_;
  {
    arg1 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg1);
  }
  arg2 = *(LocalState **)&jarg2; 
  {
    arg3 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg3);
  }
  EstimateNoiseW((double const (*))arg1,arg2,arg3);
  
  
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_EstimateNoiseW_1initialize(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  EstimateNoiseW_initialize();
}


SWIGEXPORT void JNICALL Java_EstimateNoiseMWJNI_EstimateNoiseW_1terminate(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  EstimateNoiseW_terminate();
}


#ifdef __cplusplus
}
#endif

