/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_appjax_jni_ThreadCPUUsage */

#ifndef _Included_net_appjax_jni_ThreadCPUUsage
#define _Included_net_appjax_jni_ThreadCPUUsage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uiowa_csense_runtime_compatibility_ThreadCPUUsage
 * Method:    getusage
 * Signature: ()Ledu/uiowa/csense/runtime/compatibility/ThreadCPUUsage;
 */
JNIEXPORT jobject JNICALL Java_edu_uiowa_csense_runtime_compatibility_ThreadCPUUsage_getusage
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif

