/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "rtwtypes.h"
#include "a_melcepst_types.h"

extern emxArray_real_T *emxCreate_real_T(int32_T rows, int32_T cols);


static int *new_intArray(int nelements) { 
  return (int *) calloc(nelements,sizeof(int)); 
}

static void delete_intArray(int *ary) { 
  free(ary); 
}

static int intArray_getitem(int *ary, int index) {
    return ary[index];
}
static void intArray_setitem(int *ary, int index, int value) {
    ary[index] = value;
}


static double *new_doubleArray(int nelements) { 
  return (double *) calloc(nelements,sizeof(double)); 
}

static void delete_doubleArray(double *ary) { 
  free(ary); 
}

static double doubleArray_getitem(double *ary, int index) {
    return ary[index];
}
static void doubleArray_setitem(double *ary, int index, double value) {
    ary[index] = value;
}



#include "a_melcepst_types.h"
#include "rtwtypes.h"
#include "a_melcepst_initialize.h"
#include "a_melcepst_terminate.h"

void a_melcepst_wrap(const real_T s[512], int32_T offset1, 
                     real_T fs, int32_T nc, emxArray_real_T *c, 
                     real_T r[32], int32_T offset2);
//void a_melcepst(const real_T s[512], real_T fs, int32_T nc, emxArray_real_T *c);
extern void a_melcepst_initialize(void);
extern void a_melcepst_terminate(void);
//
//


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1intArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int *)new_intArray(arg1);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1intArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  int *arg1 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(int **)&jarg1; 
  delete_intArray(arg1);
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_intArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jint jresult = 0 ;
  int *arg1 = (int *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(int **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)intArray_getitem(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_intArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
  int *arg1 = (int *) 0 ;
  int arg2 ;
  int arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(int **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  intArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  double *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (double *)new_doubleArray(arg1);
  *(double **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  double *arg1 = (double *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT jdouble JNICALL Java_a_1melcepstJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jdouble jresult = 0 ;
  double *arg1 = (double *) 0 ;
  int arg2 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (double)doubleArray_getitem(arg1,arg2);
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jdouble jarg3) {
  double *arg1 = (double *) 0 ;
  int arg2 ;
  double arg3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(double **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (double)jarg3; 
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (void *) ((arg1)->data);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_a_1melcepstJNI_emxArray_1_1common_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray__common **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1emxArray_1_1common(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray__common *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray__common *)calloc(1, sizeof(emxArray__common));
  *(emxArray__common **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1emxArray_1_1common(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray__common *arg1 = (emxArray__common *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray__common **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  boolean_T *arg2 = (boolean_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  arg2 = *(boolean_T **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  boolean_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  result = (boolean_T *) ((arg1)->data);
  *(boolean_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_a_1melcepstJNI_emxArray_1boolean_1T_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1emxArray_1boolean_1T(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_boolean_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_boolean_T *)calloc(1, sizeof(emxArray_boolean_T));
  *(emxArray_boolean_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1emxArray_1boolean_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_boolean_T *arg1 = (emxArray_boolean_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_boolean_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  creal_T *arg2 = (creal_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  arg2 = *(creal_T **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  creal_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  result = (creal_T *) ((arg1)->data);
  *(creal_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_a_1melcepstJNI_emxArray_1creal_1T_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1emxArray_1creal_1T(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_creal_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_creal_T *)calloc(1, sizeof(emxArray_creal_T));
  *(emxArray_creal_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1emxArray_1creal_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_creal_T *arg1 = (emxArray_creal_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_creal_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  result = (int32_T *) ((arg1)->data);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_a_1melcepstJNI_emxArray_1int32_1T_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_new_1emxArray_1int32_1T(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  emxArray_int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (emxArray_int32_T *)calloc(1, sizeof(emxArray_int32_T));
  *(emxArray_int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1emxArray_1int32_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_int32_T *arg1 = (emxArray_int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_int32_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  real_T *arg2 = (real_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = *(real_T **)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (real_T *) ((arg1)->data);
  *(real_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T *arg2 = (int32_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = *(int32_T **)&jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T *) ((arg1)->size);
  *(int32_T **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1allocatedSize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->allocatedSize = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1allocatedSize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T) ((arg1)->allocatedSize);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1numDimensions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (int32_T)jarg2; 
  if (arg1) (arg1)->numDimensions = arg2;
}


SWIGEXPORT jint JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1numDimensions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  int32_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (int32_T) ((arg1)->numDimensions);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1canFreeData_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  boolean_T arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  arg2 = (boolean_T)jarg2; 
  if (arg1) (arg1)->canFreeData = arg2;
}


SWIGEXPORT jshort JNICALL Java_a_1melcepstJNI_emxArray_1real_1T_1canFreeData_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  boolean_T result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(emxArray_real_T **)&jarg1; 
  result = (boolean_T) ((arg1)->canFreeData);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_delete_1emxArray_1real_1T(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  emxArray_real_T *arg1 = (emxArray_real_T *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(emxArray_real_T **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_a_1melcepst_1wrap(JNIEnv *jenv, jclass jcls, jobject jarg1, jint jarg2, jdouble jarg3, jint jarg4, jlong jarg5, jobject jarg5_, jobject jarg6, jint jarg7) {
  real_T *arg1 ;
  int32_T arg2 ;
  real_T arg3 ;
  int32_T arg4 ;
  emxArray_real_T *arg5 = (emxArray_real_T *) 0 ;
  real_T *arg6 ;
  int32_T arg7 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg5_;
  {
    arg1 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg1);  
    //arg1 = jenv->GetDirectBufferAddress(jarg1); 
    //$2 = (long)(jenv->GetDirectBufferCapacity(jarg1)); 
  }
  arg2 = (int32_T)jarg2; 
  arg3 = (real_T)jarg3; 
  arg4 = (int32_T)jarg4; 
  arg5 = *(emxArray_real_T **)&jarg5; 
  {
    arg6 = (real_T*)(*jenv)->GetDirectBufferAddress(jenv, jarg6); 
  }
  arg7 = (int32_T)jarg7; 
  a_melcepst_wrap((double const (*))arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  
  
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_a_1melcepst_1initialize(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  a_melcepst_initialize();
}


SWIGEXPORT void JNICALL Java_a_1melcepstJNI_a_1melcepst_1terminate(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  a_melcepst_terminate();
}


SWIGEXPORT jlong JNICALL Java_a_1melcepstJNI_emxCreate_1real_1T(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int32_T arg1 ;
  int32_T arg2 ;
  emxArray_real_T *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int32_T)jarg1; 
  arg2 = (int32_T)jarg2; 
  result = (emxArray_real_T *)emxCreate_real_T(arg1,arg2);
  *(emxArray_real_T **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

